/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rings_7.glb -t -d 
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh
    dobj: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Diamond: THREE.MeshStandardMaterial
  }
  //animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/rings_7.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.001']} rotation={[1.317, 0, 0]}>
        <mesh geometry={nodes.dobj.geometry} material={materials.Diamond} position={[0.001, 0.03, 0.003]} rotation={[-Math.PI / 2, 0, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/rings_7.glb', true, false)
